### ISSUE TITLE
Accordion 

### ISSUE THREAD

**Issue by chriza** [contao-bootstrap/panel#13]
Hallo,
ich habe eine Frage zum Accordeon.

Im Backend habe ich die Checkbox "Standardmaßig öffnen" nicht angewählt.
Die Variable "bootstrap_collapseIn" ist auch ohne Wert.
Es werden aber active Klassen (und entsprechende Inline-Styles) an toggler und panel-collapse übergeben.
Mache ich etwas falsch?

**Comment by dmolineus** [comment]
Should be fixed with latest 1.0.4 release.

**Comment by dmolineus** [comment]
This issue affects Contao-Bootstrap v1 which isn't supported anymore.
