### ISSUE TITLE
1.0.x - fix iOS-touch-bug

### ISSUE THREAD

**Issue by zonky2** [contao-bootstrap/panel#14]
add `role="button"` at toggler to fix touch support

```diff
-  <div class="panel-heading <?php echo $this->toggler; ?>"<?php if ($this->headlineStyle): ?> style="<?php echo $this->headlineStyle; ?>"<?php endif; ?> data-toggle="collapse"<?php if($group): ?> data-parent="#<?php echo $group; ?>"<?php endif; ?> data-target="#accordion-<?php echo $this->id; ?>">
+  <div class="panel-heading <?php echo $this->toggler; ?>"<?php if ($this->headlineStyle): ?> style="<?php echo $this->headlineStyle; ?>"<?php endif; ?> data-toggle="collapse"<?php if($group): ?> data-parent="#<?php echo $group; ?>"<?php endif; ?> data-target="#accordion-<?php echo $this->id; ?>" role="button">
```

see https://github.com/kaliber5/ember-bootstrap/issues/355#issuecomment-308904930

**Comment by dmolineus** [comment]
According to https://github.com/kaliber5/ember-bootstrap/issues/355#issuecomment-309240676 it's the wron solution as the role of the panel-heading should be `role="tab"` which is added by 75608d714dd12d7141a0130c923c97504033f340.

You'd should use the css solution suggested in your link.

**Comment by zonky2** [comment]
maybe we add at readme "known issues" with this tip to change the CSS
