### ISSUE TITLE
Klassenangabe doppelt

### ISSUE THREAD

**Issue by Olli** [contao-bootstrap/panel#2]
Bei der Ausgabe wird das Klassenattribut doppelt vergeben

```
<div class="panel-collapse collapse in" id="accordion-53" class="table"><div class="panel-body">
```

**Comment by dmolineus** [comment]
Ich kann dies nicht nachvollziehen.

Setzt du angepasste Templates ein? Das `class="table"` ist dort sehr rätselhaft und in den normalen Templates nicht zu finden.

Handelt es sich um ein Einzel-Element oder Gruppen-Element?

**Comment by Olli** [comment]
Nein ich setzte kein angepasstes Template ein. 
In beiden Fällen nutze ich ein Einelelement. Einmal einzeln stehend und einmal als Akkordion. 
Wichtig ist dass man mit der Quelltextansicht des Browsers schaut. Firebug reduziert die zweite Klassenangabe weg. 
Ich benutze von dem Panel Modul die Version 1.0.0-rc2 - Contao ist auf 3.4.2. 
Interessanterweise liefert

```
<?php echo $this->id; ?>
```

das 

```
53" class="table
```

**Comment by dmolineus** [comment]
Tatsache, die Chrome Developer Tools kürzen dies auch weg. Dann weiß ich die Ursache.

**Comment by dmolineus** [comment]
Fixed in https://github.com/contao-bootstrap/templates/commit/43ca8bd920cad7dde946a8fd003f89252c3ed905.

**Comment by Olli** [comment]
Danke.
