### ISSUE TITLE
Klassenanagabe im Akkordeonelement zieht nicht

### ISSUE THREAD

**Issue by Olli** [contao-bootstrap/panel#3]
Bei den Akkordeon-Einstellungen im Einzelelement gibt es 2 Klassenfelder.
Es ist nicht ganz klar wozu beide Felder da sind und wenn diese ausgefüllt werden schlägt sich das in  der Ausgabe nicht nieder.

**Comment by dmolineus** [comment]
Die beiden Klassenfelder stammen von Contaos Akkordion Element. Die erste Eingabe ist für das Toggle-Element gedacht (`panel-heading`), das zweite für den Collapse-Container (`panel-collapse`). 

Zur Zeit wird das erste Feld nicht übernommen (Bug Contao-Bootstrap). Das zweite wird übernommen, aber jedoch von Bootstraps Javascript überschrieben (Bug/Feature in Bootstrap). Bitte schau, ob dafür bereits ein Ticket bei twbs/bootstrap existiert und mach dort ggf. ein Ticket auf.

**Comment by Olli** [comment]
Habe zwar nichts bei TWBS/bootstrap gefunden aber mir ist das Problem eher nicht so wichtig um da jetzt einen Bugreport aufzumachen. Ich bin nur zufällig beim Rumspielen rüber gestolpert.

**Comment by dmolineus** [comment]
Okay. Interessant ist dieses Feld daher, da man dadurch mal bestimmen konnte, welches Element offen bleibt durch eine `collapse in`. Weiß nicht, seit wann es nicht mehr geht, es ging mit einer früheren Version von twbs/bootstrap definitiv mal.

**Comment by dmolineus** [comment]
Die Toggler Klasse wird nun zum Header hinzugefügt: fb7e8f1819c24cf8669b2ab039eb0a40349571c8
