### ISSUE TITLE
Aktivierte Checkbox "offen" - aria-expanded fehlt

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/panel#6]
Es wäre super, wenn nicht nur die Klasse `in` hinzugefügt wird, sondern auch im `panel-heading` bzw. `panel-collapse` jeweils das Attribut `aria-expanded="true"` bekommen würden. So könnte man das `panel-heading` einfacher per CSS ansteuern (gerade wenn man nicht alle Accordions standardmäßig öffnen will).

**Comment by dmolineus** [comment]
Pull requests are welcome. :)

**Comment by mj1985** [comment]
Selbst gelöst, da ich es gerade wieder brauchte.
Im Template: ce_accordion_start.html5 nach `data-target="#accordion-<?php echo $this->id; ?>"` folgendes einfügen:
`<?php if($this->bootstrap_collapseIn): ?> aria-expanded="true"<?php endif; ?>`

@dmolineus Ich bin gerade zu doof einen PR zu erstellen ...

**Comment by dmolineus** [comment]
Thanks. Fixed in 1.0.2
